import { CalendarDaysIcon, Table2, UsersRoundIcon } from "@/components/icons";
import { MetricCard, PracticePage, PracticePageHeader, SectionHeading } from "@/components/practice/practice-page";
import { formatCount } from "@/lib/format";
import type { AnalyticsPayload } from "@/lib/types";

export function ReportsWorkspace({ analytics }: { analytics: AnalyticsPayload }) {
  const peak = Math.max(1, ...analytics.series.map((point) => point.patient_count));
  const average = analytics.series.length ? analytics.totals.patient_count / analytics.series.length : 0;
  const newPatientLabel = analytics.totals.new_patients === 1 ? "new patient" : "new patients";
  const returningPatientLabel = analytics.totals.returning_patients === 1 ? "returning patient" : "returning patients";
  return <PracticePage><PracticePageHeader eyebrow="Practice intelligence" title="Reports" description="Clinical activity and patient flow are shown from committed records only; draft notes never inflate performance." /><section className="grid gap-3 sm:grid-cols-3"><MetricCard label="Patients" value={formatCount(analytics.totals.patient_count)} detail={`${formatCount(analytics.totals.new_patients)} ${newPatientLabel}`} tone="primary" /><MetricCard label="Returning" value={formatCount(analytics.totals.returning_patients)} detail="Committed visits in range" /><MetricCard label="Daily average" value={average.toFixed(1)} detail={`${analytics.series.length} calendar days`} /></section><section className="surface-card rounded-[1.35rem] bg-card p-4 sm:p-5"><SectionHeading title="Patient flow" description={`${date(analytics.from)} to ${date(analytics.to)}`} /><div className="mt-6 flex h-56 items-end gap-1 border-b border-border px-1" role="img" aria-label="Daily committed patient volume">{analytics.series.map((point) => <div key={point.day} className="group relative flex min-w-0 flex-1 items-end" title={`${date(point.day)}: ${point.patient_count} patients`}><span className="w-full min-w-1 rounded-t-sm bg-primary/75 transition-colors group-hover:bg-primary" style={{ height: `${Math.max(point.patient_count ? 6 : 1, (point.patient_count / peak) * 100)}%` }} /></div>)}</div><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>{date(analytics.from)}</span><span>{date(analytics.to)}</span></div></section><div className="grid gap-5 lg:grid-cols-2"><ReportCard icon={UsersRoundIcon} title="Patient mix" text={`${analytics.totals.new_patients} ${newPatientLabel} and ${analytics.totals.returning_patients} ${returningPatientLabel} in this period.`} /><ReportCard icon={CalendarDaysIcon} title="Capacity planning" text="The appointment and chair schema is ready to add utilisation, no-show and treatment-conversion reporting without inferring from visit notes." /></div></PracticePage>;
}

function ReportCard({ icon: Icon, title, text }: { icon: typeof Table2; title: string; text: string }) { return <article className="surface-card rounded-[1.35rem] bg-card p-5"><span className="grid size-10 place-items-center rounded-xl bg-primary-soft text-primary"><Icon className="size-5" aria-hidden /></span><h2 className="mt-4 text-base font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>; }
function date(value: string): string { const parsed = new Date(value.includes("T") ? value : `${value}T12:00:00+05:30`); return Number.isNaN(parsed.getTime()) ? value : new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric", timeZone: "Asia/Kolkata" }).format(parsed); }
